// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../node_modules/rescript/lib/es6/curry.js";
import * as Store from "svelte/store";

var Svelte = {};

var model = Store.writable({
      count: 0,
      name: ""
    });

var Action = {};

function e(action) {
  return function (params) {
    if (action === "decrement") {
      return Curry._1(model.update, (function (value) {
                    return {
                            count: value.count - 1 | 0,
                            name: value.name
                          };
                  }));
    } else if (action === "increment") {
      return Curry._1(model.update, (function (value) {
                    return {
                            count: value.count + 1 | 0,
                            name: value.name
                          };
                  }));
    } else if (action === "change") {
      return Curry._1(model.update, (function (value) {
                    return {
                            count: value.count,
                            name: params.srcElement.value
                          };
                  }));
    } else {
      console.warn("[Rescript]:", action, "is not a valid action...");
      return ;
    }
  };
}

export {
  Svelte ,
  model ,
  Action ,
  e ,
  
}
/* model Not a pure module */
